# Generated by Django 2.1.4 on 2019-01-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser4', '0003_auto_20190105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twogis',
            name='oid',
            field=models.FloatField(),
        ),
    ]
